#!/bin/sh

d() {
    date +%Y_%m_%d-%H_%M_%S
}

dir() {
    echo "starting with $1 ($(d))"
    cd $1
    git remote update
    LOCAL=$(git rev-parse @)
    REMOTE=$(git rev-parse '@{u}')
    BASE=$(git merge-base @ '@{u}')
    if [ $LOCAL = $REMOTE ]; then
        echo "Sleeping for 100 secs"
        sleep 120
    elif [ $LOCAL = $BASE ]; then
        git pull
        echo "starting build"
        sh ci.sh $(d)_$REMOTE $REMOTE
        echo "build finished"
    elif [ $REMOTE = $BASE ]; then
        echo "Warning: You have local changes."
    else
        echo "Error: Your local repo is broken."
        exit 1
    fi
    [ -f ci_periodically.sh ] && sh ci_periodically.sh
    echo "done with f_cking $1 ($(d))"
}

I=0

while true ; do
    ping -c 1 1.1.1.1 || { echo "[ERROR] NO INTERNET" ; sleep 30 ; continue ; }
    for projdir in $(cat /etc/dirs.ci4w1nners) ; do
        I=$(($I + 1))
        dir $projdir 2>&1 | tee -a /usr/local/var/www/log.txt
    done
    if [ $I -gt 50 ] ; then
        I=0
        fn=/usr/local/var/www/log_$(d).txt
        mv -f /usr/local/var/www/log.txt $fn
        xz -9 $fn
    fi
done
