#!/bin/sh

dir() {
    cd $1
    git remote update
    LOCAL=$(git rev-parse @)
    REMOTE=$(git rev-parse '@{u}')
    BASE=$(git merge-base @ '@{u}')
    if [ $LOCAL = $REMOTE ]; then
        echo "Sleeping for 100 secs"
        sleep 100
    elif [ $LOCAL = $BASE ]; then
        git pull
        echo "starting build"
        sh ci.sh
        echo "build finished"
    elif [ $REMOTE = $BASE ]; then
        echo "Warning: You have local changes."
    else
        echo "Error: Your clone is broken."
        exit 1
    fi
}

while true ; do
    for proj in AmplissimusApp Artillar ; do
        dir ~/$proj | while : ; do
            read line
            echo "$(date '+%d.%m.%Y %H:%M:%S') [$proj] $line"
        done
    done
done | tee -a /usr/local/var/www/log.txt
